name: dart_music_api
description: A starting point for Dart libraries or applications.
#version: 0.0.1-nullsafety.1
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0'

dependencies:
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cookie_jar: ^4.0.8
  crypto: ^3.0.6
  lyrics_parser:
    git: https://github.com/fusee-code-lab/lyrics_parser.git

dev_dependencies:
  test: ^1.25.14
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.2
  lints: ^5.1.1

